Fix macOS build

diff --git a/solenv/bin/macosx-codesign-app-bundle b/solenv/bin/macosx-codesign-app-bundle
--- a/solenv/bin/macosx-codesign-app-bundle
+++ b/solenv/bin/macosx-codesign-app-bundle
@@ -25,6 +25,7 @@ done
 APP_BUNDLE="$1"
 entitlements=
 entitlements_helper=
+entitlements_quicklookappex="--entitlements $SRCDIR/sysui/desktop/macosx/quicklookappex.entitlements"
 launch_constraint="--launch-constraint-parent $BUILDDIR/sysui/desktop/macosx/LaunchConstraint.plist"
 application_identifier=
 if test -n "$ENABLE_MACOSX_SANDBOX"; then
@@ -35,19 +36,12 @@ if test -n "$ENABLE_MACOSX_SANDBOX"; then
     application_identifier=`/usr/libexec/PlistBuddy -c "print com.apple.application-identifier"  $BUILDDIR/lo.xcent`
     # remove the key from the entitlement - only use it when signing the whole bundle in the final step
     /usr/libexec/PlistBuddy -c "delete com.apple.application-identifier"  $BUILDDIR/lo.xcent
-    # All data files are in Resources and included in the app bundle signature
-    other_files=''
     # HACK: remove donate menu entries, need to support apple-pay and be verified
     # as non profit as a bare minimum to allow asking....
     sed -I "" -e '\#<menu:menuitem menu:id=".uno:Donation"/>#d' $APP_BUNDLE/Contents/Resources/config/soffice.cfg/modules/*/menubar/menubar.xml
 else
-    # We then want to sign data files, too, hmm.
     entitlements="--entitlements $BUILDDIR/hardened_runtime.xcent"
     entitlements_helper=$entitlements
-    other_files="\
- -or -name '*.fodt' -or -name 'schema.strings' -or -name 'schema.xml' \
- -or -name '*.jar' -or -name 'LICENSE' -or -name 'LICENSE.html' \
- -or -name '*.applescript' -or -name '*.odt'"
 fi
 
 if test -z "$MACOSX_CODESIGNING_IDENTITY"; then
@@ -56,32 +50,41 @@ if test -z "$MACOSX_CODESIGNING_IDENTITY"; then
         exit 1
     fi
 
+    # Quick Look plugins will only load if with sandbox entitlements
+    find "$APP_BUNDLE" -name 'QuickLook*.appex' -type d |
+    while read appex; do
+        codesign --force --prefix=$MACOSX_BUNDLE_IDENTIFIER. --sign - $entitlements_quicklookappex "$appex" || exit 1
+    done
+
     # Skip codesigning for non-release builds if there is no identity set but
     # set entitlements to allow Xcode's Instruments application to connect to
     # the application. Note: the following command fails on some Mac Intel
     # machines, and since this not a release build, ignore any failures.
-    codesign --force --identifier="${MACOSX_BUNDLE_IDENTIFIER}" --sign - $entitlements "$APP_BUNDLE"
+    # Related: tdf#159529 fix increasing failures when setting entitlements
+    # Starting in one of the Xcode versions 15.2 or earlier, setting the
+    # entitlements without a certificate started failing on Mac Silicon. 
+    # The hacky solution is to make a copy of the application's executable,
+    # set the entitlements on that binary only, and then move the copied
+    # binary back.
+    rm -f "$APP_BUNDLE/Contents/MacOS/soffice.withentitlements"
+    cp "$APP_BUNDLE/Contents/MacOS/soffice" "$APP_BUNDLE/Contents/MacOS/soffice.withentitlements"
+    if codesign --force --identifier="${MACOSX_BUNDLE_IDENTIFIER}" --sign - $entitlements "$APP_BUNDLE/Contents/MacOS/soffice.withentitlements"; then
+        mv "$APP_BUNDLE/Contents/MacOS/soffice.withentitlements" "$APP_BUNDLE/Contents/MacOS/soffice"
+    else
+        rm "$APP_BUNDLE/Contents/MacOS/soffice.withentitlements"
+    fi
+
     exit 0
 fi
-
-# Sign jnilibs first as workaround for signing issue on old baseline
-# order matters/screws things up otherwise
-find -d "$APP_BUNDLE" \( -name '*.jnilib' \) ! -type l |
-    while read file; do
-    id=`echo ${file#${APP_BUNDLE}/Contents/} | sed -e 's,/,.,g'`
-    codesign --force --identifier=$MACOSX_BUNDLE_IDENTIFIER.$id --sign "$MACOSX_CODESIGNING_IDENTITY" "$file" || exit 1
-done
 
 # Sign dylibs
 #
 # The dylibs in the Python framework are called *.so. Go figure
 #
-# On Mavericks also would like to have data files signed...
-# add some where it makes sense. Make a depth-first search to sign the contents
-# of e.g. the spotlight plugin before attempting to sign the plugin itself
+# Make a depth-first search to sign the contents of e.g. the spotlight plugin
+# before attempting to sign the plugin itself
 
-find "$APP_BUNDLE" \( -name '*.dylib' -or -name '*.dylib.*' -or -name '*.so' \
-        $other_files \) ! -type l |
+find "$APP_BUNDLE" \( -name '*.dylib' -or -name '*.dylib.*' -or -name '*.so' -or -name '*.jnilib' \) ! -type l |
 while read file; do
     id=`echo ${file#${APP_BUNDLE}/Contents/} | sed -e 's,/,.,g'`
     codesign --force --identifier=$MACOSX_BUNDLE_IDENTIFIER.$id --sign "$MACOSX_CODESIGNING_IDENTITY" "$file" || exit 1
@@ -94,7 +97,7 @@ find "$APP_BUNDLE"/Contents -name '*.app' -type d |
 while read app; do
     # Assume the app has a XML (and not binary) Info.plist
     id=`grep -A 1 '<key>CFBundleIdentifier</key>' "$app/Contents/Info.plist" | tail -1 | sed -e 's,.*<string>,,' -e 's,</string>.*,,'`
-    codesign --timestamp --options=runtime --force --identifier=$id --sign "$MACOSX_CODESIGNING_IDENTITY" $entitlements $launch_constraint "$app" || exit 1$APP_BUNDLE/Contents/MacOS"
+    codesign --timestamp --options=runtime --force --identifier=$id --sign "$MACOSX_CODESIGNING_IDENTITY" $entitlements $launch_constraint "$app" || exit 1
 done
 
 # Then .framework ones. Again, be generic just for kicks.
@@ -108,10 +111,10 @@ while read framework; do
 	    if test -d $version/bin; then
 		# files in bin are not covered by signing the framework...
 		for scriptorexecutable in $(find $version/bin/ -type f); do
-		    codesign --timestamp --options=runtime --force --identifier=$id --sign "$MACOSX_CODESIGNING_IDENTITY" "$scriptorexecutable" || exit 1
+		    codesign --timestamp --options=runtime --force --identifier=$id --sign "$MACOSX_CODESIGNING_IDENTITY" $launch_constraint "$scriptorexecutable" || exit 1
 		done
 	    fi
-            codesign --force --identifier=$id --sign "$MACOSX_CODESIGNING_IDENTITY" "$version" || exit 1
+            codesign --force --identifier=$id --sign "$MACOSX_CODESIGNING_IDENTITY" $launch_constraint "$version" || exit 1
 	fi
     done
 done
@@ -123,6 +126,12 @@ while read bundle; do
     codesign --force --prefix=$MACOSX_BUNDLE_IDENTIFIER. --sign "$MACOSX_CODESIGNING_IDENTITY" "$bundle" || exit 1
 done
 
+# Quick Look plugins will only load if with sandbox entitlements
+find "$APP_BUNDLE" -name 'QuickLook*.appex' -type d |
+while read appex; do
+    codesign --force --timestamp --options=runtime --prefix=$MACOSX_BUNDLE_IDENTIFIER. --sign "$MACOSX_CODESIGNING_IDENTITY" $entitlements_quicklookappex "$appex"|| exit 1
+done
+
 # Sign executables
 
 find "$APP_BUNDLE/Contents/MacOS" -type f |
@@ -130,12 +139,11 @@ while read file; do
     case "$file" in
 	*/soffice)
 	    ;;
-        */unopkg)
-	*)
+	*/unopkg)
 	    id=`echo ${file#${APP_BUNDLE}/Contents/} | sed -e 's,/,.,g'`
 	    codesign --force --timestamp --options=runtime --identifier=$MACOSX_BUNDLE_IDENTIFIER.$id --sign "$MACOSX_CODESIGNING_IDENTITY" $entitlements_helper "$file" || exit 1
 	    ;;
-        *)
+	*)
 	    id=`echo ${file#${APP_BUNDLE}/Contents/} | sed -e 's,/,.,g'`
 	    codesign --force --timestamp --options=runtime --identifier=$MACOSX_BUNDLE_IDENTIFIER.$id --sign "$MACOSX_CODESIGNING_IDENTITY" $entitlements_helper $launch_constraint "$file" || exit 1
 	    ;;
